openapi: 3.0.0
info:
  title:  Magic 8-Ball API
  description: An API that answers your question!
  version: 0.0.1
  
servers: 
  - url: http://localhost:8080
    description: Local dev server
    
paths:
  /magic:
    post:
      summary: Returns an answer to the user's question.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Answer'
      responses:
        '201':
          description: Created
        '422':
          description: The question provided is not valid.
        default:
          description: Unexpected error
components:
  schemas:
    Answer:
      properties:
        question:
          type: string
        answer:
          type: string